/**
 * Stable error codes thrown by the Tonder Web SDK.
 *
 * Public methods surface failures as {@link AppError} instances with one of
 * these codes, so integrations can branch without parsing human-readable
 * messages.
 */
export enum ErrorKeyEnum {
  INIT_ERROR = 'INIT_ERROR',
  CREATE_ERROR = 'CREATE_ERROR',
  INVALID_TYPE = 'INVALID_TYPE',
  STATE_ERROR = 'STATE_ERROR',
  FETCH_BUSINESS_ERROR = 'FETCH_BUSINESS_ERROR',
  INVALID_CONFIG = 'INVALID_CONFIG',
  MERCHANT_CREDENTIAL_REQUIRED = 'MERCHANT_CREDENTIAL_REQUIRED',
  INVALID_PAYMENT_REQUEST = 'INVALID_PAYMENT_REQUEST',
  INVALID_PAYMENT_REQUEST_CARD_PM = 'INVALID_PAYMENT_REQUEST_CARD_PM',
  INVALID_COMPONENT_TYPE = 'INVALID_COMPONENT_TYPE',
  ENVIRONMENT_REQUIRED = 'ENVIRONMENT_REQUIRED',
  FETCH_CARDS_ERROR = 'FETCH_CARDS_ERROR',
  FETCH_TRANSACTION_ERROR = 'FETCH_TRANSACTION_ERROR',
  CUSTOMER_AUTH_TOKEN_NOT_VALID = 'CUSTOMER_AUTH_TOKEN_NOT_VALID',
  SAVE_CARD_ERROR = 'SAVE_CARD_ERROR',
  REMOVE_CARD_ERROR = 'REMOVE_CARD_ERROR',
  PAYMENT_PROCESS_ERROR = 'PAYMENT_PROCESS_ERROR',
  INVALID_CARD_DATA = 'INVALID_CARD_DATA',
  SAVE_CARD_PROCESS_ERROR = 'SAVE_CARD_PROCESS_ERROR',
  CUSTOMER_OPERATION_ERROR = 'CUSTOMER_OPERATION_ERROR',
  FETCH_PAYMENT_METHODS_ERROR = 'FETCH_PAYMENT_METHODS_ERROR',
  FETCH_PAYMENT_METHOD_BANKS_ERROR = 'FETCH_PAYMENT_METHOD_BANKS_ERROR',
  INVALID_APM_CONFIG = 'INVALID_APM_CONFIG',
  INVALID_VAULT_TOKEN = 'INVALID_VAULT_TOKEN',
  VAULT_TOKEN_ERROR = 'VAULT_TOKEN_ERROR',
  SECURE_TOKEN_INVALID = 'SECURE_TOKEN_INVALID',
  SECURE_TOKEN_REQUIRED = 'SECURE_TOKEN_REQUIRED',
  MISSING_CUSTOMER = 'MISSING_CUSTOMER',
  INVALID_EMAIL = 'INVALID_EMAIL',
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  SECURE_FIELDS_LOAD_ERROR = 'SECURE_FIELDS_LOAD_ERROR',
  ACQUIRER_LOAD_ERROR = 'ACQUIRER_LOAD_ERROR',
  MOUNT_COLLECT_ERROR = 'MOUNT_COLLECT_ERROR',
  CARD_ON_FILE_DECLINED = 'CARD_ON_FILE_DECLINED',
  REQUEST_ABORTED = 'REQUEST_ABORTED',
  REQUEST_FAILED = 'REQUEST_FAILED',
  POLL_TIMEOUT_ERROR = 'POLL_TIMEOUT_ERROR',
  THREEDS_REDIRECTION_ERROR = 'THREEDS_REDIRECTION_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
